# Full deployment configuration - both app and database
services:
  app:
    image: gussttaav/g-commerce-backend:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopping
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-http}
      LOG_PATH: /app/logs
      LOG_ARCHIVE: /app/logs/archive
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./certs:/certs
      - app-logs:/app/logs
    networks:
      - spring-mysql-network

  mysql:
    image: gussttaav/g-commerce-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-mysql-network

volumes:
  mysql-data:
  app-logs:

networks:
  spring-mysql-network:
    driver: bridge