spring:
  application:
    name: gestion-tienda
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

# Default admin user credentials
admin:
  default:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    nombre: ${ADMIN_NAME}

# CORS (Cross-Origin Resource Sharing) configuration
cors:
  allowed-origins: ${CORS_ORIGINS}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type,X-Requested-With

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.mitienda.gestion_tienda
  paths-to-match: /api/**