name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run PMD
        run: mvn pmd:check

  build-and-push:
    runs-on: ubuntu-latest
    needs: quality-check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the database image
      - name: Build and push database image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.db
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/g-commerce-mysql:latest
      
      # Build and push the application image
      - name: Build and push application image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/g-commerce-backend:latest

      # Update Docker Hub Description for Backend App
      - name: Update Backend Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/g-commerce-backend
          readme-filepath: ./DOCKER.md
          short-description: "Spring Boot E-commerce API - Backend Application"

      # Update Docker Hub Description for Database
      - name: Update Database Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/g-commerce-mysql
          readme-filepath: ./DOCKER_DB.md
          short-description: "MySQL Database for G-Commerce with pre-configured schema"